export const LOGIN = "LOGIN";
export const QUESTION_READY = "QUESTION_READY";
export const QUESTION_GO = "QUESTION_GO";
export const QUESTION_ANSWER = "QUESTION_ANSWER";
export const QUESTION_CORRECTION = "QUESTION_CORRECTION";
export const GAME_END = "GAME_END";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const FOUND_SERVER = "FOUND_SERVER";
export const GAME_FINISHED = "GAME_FINISHED";

export const REQUEST_DATA = "REQUEST_DATA";
export const RECEIVE_DATA = "RECEIVE_DATA";
